---
- name: Créer les répertoires nécessaires
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ web_root }}"
    - "{{ nginx_conf_dir }}"

- name: Copier la configuration Nginx
  template:
    src: "default.conf.j2"
    dest: "{{ nginx_conf_dir }}/default.conf"
  notify: Restart Nginx
