---
- name: Installer Docker et Docker-Compose
  apt:
    name:
      - docker.io
      - docker-compose
    state: present
    update_cache: yes

- name: Démarrer et activer Docker
  systemd:
    name: docker
    state: started
    enabled: yes
